### ISSUE TITLE
Any idea on the EER performance of this model in SV task?

### ISSUE THREAD

**Issue by aliencaocao** [nttcslab/m2d#3]
Trying to compare it with https://huggingface.co/nvidia/speakerverification_en_titanet_large

**Comment by daisukelab** [comment]
Hi @aliencaocao ,
I am sorry to be late. I was interested, but executing the evaluation took a long time.

I was testing our M2D variant for speech (M2D-S), in which we trained M2D on LibriSpeech (https://arxiv.org/abs/2305.14079).
The result for Speaker Verification (EER%) with the M2D-S was 5.74% on the SUPERB benchmark; it turns out that ours is better than wav2vec2.0, while WavLM and HuBERT are better than ours.

![image](https://github.com/nttcslab/m2d/assets/14831220/b593e7e7-24e7-45fa-a51b-b01cfd079151)

However, I do not know how to compare with the result in your link: Speaker Verification (EER%) on the https://huggingface.co/nvidia/speakerverification_en_titanet_large

Version | Model | Model Size | VoxCeleb1 (Cleaned trial file)
-- | -- | -- | --
1.10.0 | TitaNet-Large | 23M | 0.66

**Comment by aliencaocao** [comment]
Hi, thanks so much for this. I have checked the paper and they report the EER in %, so it actually got 0.66% EER on VoxCeleb1, which is way smaller than the results you listed. I think that the test set is difference as Nvidia used some 'cleaned trial file' thing.
Paper: https://arxiv.org/abs/2110.04410
![image](https://github.com/nttcslab/m2d/assets/20109683/6af28130-ea55-45d3-9b93-8a889b3cba0d)

**Comment by daisukelab** [comment]
Thanks for raising this issue. We summarized the ASV results with our models in the recently submitted paper.
Closing this issue for now. Please feel free to re-open.
